// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ActivitiesFields {}

export interface Activities extends OstDocument<ActivitiesFields> {}

export type ActivitiesField = keyof Activities
