// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface BoardFields {}

export interface Board extends OstDocument<BoardFields> {}

export type BoardField = keyof Board
