// Generated by Outstatic - do not edit manually

import type { News, NewsFields } from './news'
import type { Pages, PagesFields } from './pages'

export type CollectionName = 'news' | 'pages'

export type SingletonName = never

export interface Collections {
  'news': News
  'pages': Pages
}

export interface Singletons {
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = NewsFields | PagesFields
