// Generated by Outstatic - do not edit manually

import type { Activities, ActivitiesFields } from './activities'
import type { Board, BoardFields } from './board'
import type { Members, MembersFields } from './members'
import type { News, NewsFields } from './news'
import type { Pages, PagesFields } from './pages'

export type CollectionName = 'activities' | 'board' | 'members' | 'news' | 'pages'

export type SingletonName = never

export interface Collections {
  'activities': Activities
  'board': Board
  'members': Members
  'news': News
  'pages': Pages
}

export interface Singletons {
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = ActivitiesFields | BoardFields | MembersFields | NewsFields | PagesFields
