// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface MembersFields {}

export interface Members extends OstDocument<MembersFields> {}

export type MembersField = keyof Members
