// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface NewsFields {}

export interface News extends OstDocument<NewsFields> {}

export type NewsField = keyof News
