// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface PagesFields {}

export interface Pages extends OstDocument<PagesFields> {}

export type PagesField = keyof Pages
